In [1]:
import random
import numpy as np
# from .estimaciones_utils import generate_random_sparse_array, generate_random_array, generate_random_floats

In [9]:
generate_random_array((1,3), -5,5)

[[4.343882692397402, -3.4256181742049074, -2.8341380464092847]]

In [5]:
generate_random_sparse_array((6,4), -5,5,7)

[[0.9187155375255109, 0, 0, 0],
 [0, 0, 0, -2.611993426223914],
 [0.4339590958559878, 0, 0, 0],
 [0, 0, 0, 0],
 [4.320883965752028, 0, 0, -2.2097693293071097],
 [0, 3.3719549531660764, 0, 4.407677424763465]]

In [10]:
random.uniform((1,3))

TypeError: Random.uniform() missing 1 required positional argument: 'b'

In [19]:
np.diag(generate_random_array((6,), -4,4))

array([2.84070886])

In [29]:
def generate_random_floats(x, start_range, end_range):
    """
    Generates a list of random floats.

    Parameters:
    x (int): Number of random floats to generate.
    start_range (int): Start of the range (inclusive).
    end_range (int): End of the range (inclusive).

    Returns:
    list: List of random floats.
    """
    if x <= 0:
        raise ValueError("The number of random floats must be a positive integer.")
    if start_range > end_range:
        raise ValueError("Start of the range must be less than or equal to the end of the range.")
    
    return [random.uniform(start_range, end_range) for _ in range(x)]

In [31]:
np.diag(generate_random_floats(4, -4,4))

array([[-1.04892995,  0.        ,  0.        ,  0.        ],
       [ 0.        ,  3.58390733,  0.        ,  0.        ],
       [ 0.        ,  0.        ,  0.2354073 ,  0.        ],
       [ 0.        ,  0.        ,  0.        , -1.69566103]])

In [1]:
condition = False
i = 0
while condition == False:
    print(i)
    i += 1
    if i >=3:
        condition = True
        

0
1
2


In [2]:
type(np.zeros(1))

numpy.ndarray

In [3]:
unidimensional_array = np.array([1, 2, 3, 4, 5])
print(unidimensional_array)

[1 2 3 4 5]


In [6]:
a = np.array([1.001])
a[0]

np.float64(1.001)

In [8]:
beta_lower = -100*np.ones((1,1))
beta_upper = np.zeros((1,1))

In [12]:
beta_lower

array([[-100.]])

In [13]:
beta_upper

array([[0.]])